/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SendRouteImport } from './routes/send'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as ClaimGiftIdRouteImport } from './routes/claim.$giftId'
import { Route as GiftsIndexRouteImport } from './routes/gifts.index'
import { Route as GiftsGiftIdRouteImport } from './routes/gifts.$giftId'
import { Route as InviteCampaignIdInvitationIdRouteImport } from './routes/invite.$campaignId.$invitationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimGiftIdRoute = ClaimGiftIdRouteImport.update({
  id: '/claim/$giftId',
  path: '/claim/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsIndexRoute = GiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsGiftIdRoute = GiftsGiftIdRouteImport.update({
  id: '/gifts/$giftId',
  path: '/gifts/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCampaignIdInvitationIdRoute =
  InviteCampaignIdInvitationIdRouteImport.update({
    id: '/invite/$campaignId/$invitationId',
    path: '/invite/$campaignId/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/claim/$giftId': typeof ClaimGiftIdRoute
  '/gifts/$giftId': typeof GiftsGiftIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/gifts/': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/claim/$giftId': typeof ClaimGiftIdRoute
  '/gifts/$giftId': typeof GiftsGiftIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/gifts': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/claim/$giftId': typeof ClaimGiftIdRoute
  '/gifts/$giftId': typeof GiftsGiftIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/gifts/': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns/'
    | '/gifts/'
    | '/invite/$campaignId/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns'
    | '/gifts'
    | '/invite/$campaignId/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns/'
    | '/gifts/'
    | '/invite/$campaignId/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  ProfileRoute: typeof ProfileRoute
  SendRoute: typeof SendRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  ClaimGiftIdRoute: typeof ClaimGiftIdRoute
  GiftsGiftIdRoute: typeof GiftsGiftIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  GiftsIndexRoute: typeof GiftsIndexRoute
  InviteCampaignIdInvitationIdRoute: typeof InviteCampaignIdInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$giftId': {
      id: '/claim/$giftId'
      path: '/claim/$giftId'
      fullPath: '/claim/$giftId'
      preLoaderRoute: typeof ClaimGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/': {
      id: '/gifts/'
      path: '/gifts'
      fullPath: '/gifts/'
      preLoaderRoute: typeof GiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/$giftId': {
      id: '/gifts/$giftId'
      path: '/gifts/$giftId'
      fullPath: '/gifts/$giftId'
      preLoaderRoute: typeof GiftsGiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$campaignId/$invitationId': {
      id: '/invite/$campaignId/$invitationId'
      path: '/invite/$campaignId/$invitationId'
      fullPath: '/invite/$campaignId/$invitationId'
      preLoaderRoute: typeof InviteCampaignIdInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  ProfileRoute: ProfileRoute,
  SendRoute: SendRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  ClaimGiftIdRoute: ClaimGiftIdRoute,
  GiftsGiftIdRoute: GiftsGiftIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  GiftsIndexRoute: GiftsIndexRoute,
  InviteCampaignIdInvitationIdRoute: InviteCampaignIdInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
