/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as SendRouteRouteImport } from './routes/send/route'
import { Route as ClaimGiftIdRouteRouteImport } from './routes/claim/$giftId/route'
import { Route as GGiftIdRouteRouteImport } from './routes/g/$giftId/route'
import { Route as GiftsIndexRouteImport } from './routes/gifts/index'
import { Route as GiftsGiftIdRouteRouteImport } from './routes/gifts/$giftId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRouteRoute = SendRouteRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimGiftIdRouteRoute = ClaimGiftIdRouteRouteImport.update({
  id: '/claim/$giftId',
  path: '/claim/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const GGiftIdRouteRoute = GGiftIdRouteRouteImport.update({
  id: '/g/$giftId',
  path: '/g/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsIndexRoute = GiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsGiftIdRouteRoute = GiftsGiftIdRouteRouteImport.update({
  id: '/gifts/$giftId',
  path: '/gifts/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/send': typeof SendRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/g/$giftId': typeof GGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/gifts/': typeof GiftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/send': typeof SendRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/g/$giftId': typeof GGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/gifts': typeof GiftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/send': typeof SendRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/g/$giftId': typeof GGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/gifts/': typeof GiftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/send'
    | '/claim/$giftId'
    | '/g/$giftId'
    | '/gifts/$giftId'
    | '/gifts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/send'
    | '/claim/$giftId'
    | '/g/$giftId'
    | '/gifts/$giftId'
    | '/gifts'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/send'
    | '/claim/$giftId'
    | '/g/$giftId'
    | '/gifts/$giftId'
    | '/gifts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRouteRoute: typeof HelpRouteRoute
  SendRouteRoute: typeof SendRouteRoute
  ClaimGiftIdRouteRoute: typeof ClaimGiftIdRouteRoute
  GGiftIdRouteRoute: typeof GGiftIdRouteRoute
  GiftsGiftIdRouteRoute: typeof GiftsGiftIdRouteRoute
  GiftsIndexRoute: typeof GiftsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$giftId': {
      id: '/claim/$giftId'
      path: '/claim/$giftId'
      fullPath: '/claim/$giftId'
      preLoaderRoute: typeof ClaimGiftIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$giftId': {
      id: '/g/$giftId'
      path: '/g/$giftId'
      fullPath: '/g/$giftId'
      preLoaderRoute: typeof GGiftIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/': {
      id: '/gifts/'
      path: '/gifts'
      fullPath: '/gifts/'
      preLoaderRoute: typeof GiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/$giftId': {
      id: '/gifts/$giftId'
      path: '/gifts/$giftId'
      fullPath: '/gifts/$giftId'
      preLoaderRoute: typeof GiftsGiftIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRouteRoute: HelpRouteRoute,
  SendRouteRoute: SendRouteRoute,
  ClaimGiftIdRouteRoute: ClaimGiftIdRouteRoute,
  GGiftIdRouteRoute: GGiftIdRouteRoute,
  GiftsGiftIdRouteRoute: GiftsGiftIdRouteRoute,
  GiftsIndexRoute: GiftsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
