/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as SendRouteRouteImport } from './routes/send/route'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsCampaignIdRouteRouteImport } from './routes/campaigns/$campaignId/route'
import { Route as CampaignsNewRouteRouteImport } from './routes/campaigns/new/route'
import { Route as ClaimGiftIdRouteRouteImport } from './routes/claim/$giftId/route'
import { Route as GiftsIndexRouteImport } from './routes/gifts/index'
import { Route as GiftsGiftIdRouteRouteImport } from './routes/gifts/$giftId/route'
import { Route as InviteCampaignIdInvitationIdRouteRouteImport } from './routes/invite/$campaignId/$invitationId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRouteRoute = SendRouteRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRouteRoute =
  CampaignsCampaignIdRouteRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsNewRouteRoute = CampaignsNewRouteRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimGiftIdRouteRoute = ClaimGiftIdRouteRouteImport.update({
  id: '/claim/$giftId',
  path: '/claim/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsIndexRoute = GiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsGiftIdRouteRoute = GiftsGiftIdRouteRouteImport.update({
  id: '/gifts/$giftId',
  path: '/gifts/$giftId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCampaignIdInvitationIdRouteRoute =
  InviteCampaignIdInvitationIdRouteRouteImport.update({
    id: '/invite/$campaignId/$invitationId',
    path: '/invite/$campaignId/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/send': typeof SendRouteRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRoute
  '/campaigns/new': typeof CampaignsNewRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/gifts/': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/send': typeof SendRouteRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRoute
  '/campaigns/new': typeof CampaignsNewRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/gifts': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/send': typeof SendRouteRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRoute
  '/campaigns/new': typeof CampaignsNewRouteRoute
  '/claim/$giftId': typeof ClaimGiftIdRouteRoute
  '/gifts/$giftId': typeof GiftsGiftIdRouteRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/gifts/': typeof GiftsIndexRoute
  '/invite/$campaignId/$invitationId': typeof InviteCampaignIdInvitationIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns/'
    | '/gifts/'
    | '/invite/$campaignId/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns'
    | '/gifts'
    | '/invite/$campaignId/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/profile'
    | '/send'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/claim/$giftId'
    | '/gifts/$giftId'
    | '/campaigns/'
    | '/gifts/'
    | '/invite/$campaignId/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRouteRoute: typeof HelpRouteRoute
  ProfileRouteRoute: typeof ProfileRouteRoute
  SendRouteRoute: typeof SendRouteRoute
  CampaignsCampaignIdRouteRoute: typeof CampaignsCampaignIdRouteRoute
  CampaignsNewRouteRoute: typeof CampaignsNewRouteRoute
  ClaimGiftIdRouteRoute: typeof ClaimGiftIdRouteRoute
  GiftsGiftIdRouteRoute: typeof GiftsGiftIdRouteRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  GiftsIndexRoute: typeof GiftsIndexRoute
  InviteCampaignIdInvitationIdRouteRoute: typeof InviteCampaignIdInvitationIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$giftId': {
      id: '/claim/$giftId'
      path: '/claim/$giftId'
      fullPath: '/claim/$giftId'
      preLoaderRoute: typeof ClaimGiftIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/': {
      id: '/gifts/'
      path: '/gifts'
      fullPath: '/gifts/'
      preLoaderRoute: typeof GiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/$giftId': {
      id: '/gifts/$giftId'
      path: '/gifts/$giftId'
      fullPath: '/gifts/$giftId'
      preLoaderRoute: typeof GiftsGiftIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$campaignId/$invitationId': {
      id: '/invite/$campaignId/$invitationId'
      path: '/invite/$campaignId/$invitationId'
      fullPath: '/invite/$campaignId/$invitationId'
      preLoaderRoute: typeof InviteCampaignIdInvitationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRouteRoute: HelpRouteRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  SendRouteRoute: SendRouteRoute,
  CampaignsCampaignIdRouteRoute: CampaignsCampaignIdRouteRoute,
  CampaignsNewRouteRoute: CampaignsNewRouteRoute,
  ClaimGiftIdRouteRoute: ClaimGiftIdRouteRoute,
  GiftsGiftIdRouteRoute: GiftsGiftIdRouteRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  GiftsIndexRoute: GiftsIndexRoute,
  InviteCampaignIdInvitationIdRouteRoute:
    InviteCampaignIdInvitationIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
